blog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'blog.views.index', name='home'),
    url(r'^view_posts/(?P<page_num>[0-9]*)/$', 'blog.views.view_posts', name='view_posts'),
    url(r'^view_post/(?P<post_id>[0-9]*)/$', 'blog.views.view_post', name='view_post'),
    url(r'^create_post/$', 'blog.views.create_post', name='create_post'),
    url(r'^delete_post/(?P<post_id>[0-9]*)/$', 'blog.views.delete_post', name='delete_post'),
    url(r'^register/$', 'blog.views.register', name='register'),
    url(r'^login/$', 'blog.views.login', name='login'),
    url(r'^logout/$', 'blog.views.logout', name='logout'),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=60)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.OneToOneField(User)

    def __unicode__(self):
        return u'%s created on %s' % (self.title, self.created)

    class Meta():
        ordering = ['-created']


class Comment(models.Model):
    post = models.ForeignKey(Post)
    body = models.TextField()
    created_by = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s commented on \'%s\' post on %s' % (self.user_name, self.post.title, self.created)

    class Meta():
        ordering = ['created']

blog/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="/static/blog.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="/static/style.css" />
    {% if messages %}
        <script>
            $(document).ready(function(){
                $("#messages").show().delay(5000).hide(400);
            });
        </script>
    {% endif %}
    {% block js %}
    {% endblock %}
    <title>Andy's Blog - {% block title %}{% endblock %}</title>
</head>

<body>
<div id="container">
    <div id="header">
        <h1>Andy's <span class="off">Blog</span></h1>
            <!--<h2>A template by Bryant Smith</h2>-->
    </div>
        
    <div id="menu"></div>
        
        <div id="leftmenu">

            <div id="leftmenu_top"></div>

				<div id="leftmenu_main">    
                
                <h3>Links</h3>
                        
                <ul>
                    <li id="home"><a id="home_link" href={% url "home" %}>Home</a></li>
                    <li id="login"
                        {% if user.is_authenticated %}
                            style="display: none"
                        {% endif %}>
                        <a id="login_link" href="{% url "login" %}">Login</a></li>
                    <li id="register"
                        {% if user.is_authenticated %}
                            style="display: none"
                        {% endif %}>
                        <a id="register" href="{% url "register" %}">Register</a></li>
                    <li><a id="view_posts" href="{% url "view_posts" page_num="1" %}">View Posts</a></li>
                    <li id="create_post"
                        {% if not user.is_authenticated %}
                            style="display: none"
                        {% endif %}>
                    <a id="create_post_link" href="{% url "create_post" %}">Create Post</a></li>
                    <li id="logout_link"
                        {% if not user.is_authenticated %}
                            style="display: none;"
                    {% endif %}>
                    <a id="logout" href="{% url "logout" %}">Logout</a></li>
                </ul>

			    </div>
                
                
              <div id="leftmenu_bottom"></div>
        </div>
        
        
        
        
		<div id="content">
            <div id="nav">
                {% block nav %}<a href="{% url "home" %}">Home</a>{% endblock %}
                <br>
            </div>
            <div id="content_top"></div>
                <div id="content_main">
                    {% block content %}{% endblock %}
                </div>
            <div id="content_bottom"></div>
            
            <!--<div id="footer"><h3><a href="http://www.bryantsmith.com">florida web design</a></h3></div> -->
      </div>
   </div>
</div>
<div id="messages">
{% if messages %}
   {% for message in messages %}
      <p>{{ message }}</p>
   {% endfor %}
{% endif %}
</div>
</body>
</html>

blog/templates/create_post.html
{% extends "base.html" %}
{% block title %}Create Post{% endblock %}
{% block nav %}
   <a href="{% url "home" %}">Home</a> &gt;
   <a href="{% url "create_post" %}">Create Post</a>
{% endblock %}
{% block content %}
{% if error %}
   <p style="color: red;">{{ error }}</p>
{% else %}
   <h2>Create Post</h2>
   {% if form.errors %}
      <p style="color: red;">
         Please correct the error{{ form.errors|pluralize }} below.
      </p>
   {% endif %}

   <form action="" method="post">{% csrf_token %}
      <table>
         {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
   </form>
{% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block nav %}
    <a href="{% url "home" %}">Home</a>
{% endblock %}
{% block content %}
    <h2>Welcome to my Blog</h2>
    <p>This is a demo blog site written in Django, and hosted on Google's App Engine.</p>
    <p>The source code for this will be hosted on GitHub shortly</p>
{% endblock %}

blog/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block nav %}
   <a href="{% url "home" %}">Home</a> &gt; 
   <a href="{% url "login" %}">Login</a>
{% endblock %}
{% block content %}
{% if error %}
   <p style="color: red;">{{ error }}</p>
{% else %}
   <h2>Register</h2>
   {% if form.errors %}
      <p style="color: red;">
         Please correct the error{{ form.errors|pluralize }} below.
      </p>
   {% endif %}

   <form action="" method="post">{% csrf_token %}
      <table>
         {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
   </form>
{% endif %}
{% endblock %}

blog/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block nav %}
   <a href="{% url "home" %}">Home</a> &gt; 
   <a href="{% url "register" %}">Register</a>
{% endblock %}
{% block content %}
{% if error %}
   <p style="color: red;">{{ error }}</p>
{% else %}
   <h2>Register</h2>
   {% if form.errors %}
      <p style="color: red;">
         Please correct the error{{ form.errors|pluralize }} below.
      </p>
   {% endif %}

   <form action="" method="post">{% csrf_token %}
      <table>
         {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
   </form>
{% endif %}
{% endblock %}

blog/templates/view_post.html
{% extends "base.html" %}
{% load markup %}
{% block title %}View Post: {{ post.title }}{% endblock %}
{% block nav %}
    <a href="{% url "home" %}">Home</a> &gt
    <a href="{% url "view_post" post_id=post.id %}">View Post '{{ post.title }}'</a>
{% endblock %}
{% block content %}
    <br>
    <h3>{{ post.title }}</h3>
    <hr>
    {{ post.body|markdown }}
    <hr>
    <span style="float: left;"><a id="show_comments" href="#">Show Comments</a></span>
    {% ifequal post.created_by user %}
        <span style="float: right;">
            <a id="delete_post" href="{% url "delete_post" post_id=post.id %}">Delete post</a>
        </span>
    {% endifequal %}
    <div id="comments" style="display: none;">
        <br>
        <h3>Comments:</h3>
        <table>
        {% for comment in post.comment_set.all %}
            <tr><td>{{ comment.created_by }} wrote: </td><td>{{ comment.body }}</td></tr>
        {% empty %}
            <tr><td><i>There are currently no comments to display</i></td></tr>
        {%  endfor %}
        </table>
        <br>
        {% if error %}
            <p style="color: red;">{{ error }}</p>
        {% else %}
            <b>Leave a comment:</b>
            {% if form.errors %}
                <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
                </p>
            {% endif %}

            <form action="" method="post">{% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Submit">
            </form>
        {% endif %}
    </div>
    <div id="dialog-confirm" style="display: none;" title="Delete Post?">
        <p><span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;">
        </span>Are you sure you want to delete this post?</p>
   </div>
{% endblock %}

blog/templates/view_posts.html
{% extends "base.html" %}
{% load tags %}
{% load markup %}
{% block title %}View Posts - Page {{ page_num }} of {{ max_page }}{% endblock %}
{% block nav %}
    <a href="{% url "home" %}">Home</a>
    {% ifnotequal request.path "/"  %}
        &gt;
        <a href="{% url "view_posts" page_num=page_num %}">View Posts - Page {{ page_num }} of {{ max_page }}</a>
    {% endifnotequal %}
{% endblock %}
{% block content %}
    <br>
    {% if posts %}
        <table>
        {% for post in posts %}
            <tr><td><b><a href="{% url "view_post" post_id=post.id %}">{{ post.title }}</a></b></td></tr>
            <tr><td>{{ post.body|truncatesmart|markdown }}</td></tr>
        {% endfor %}
        {% comment %}
        Display the pagination links providing that there is more than one page to display, otherwise
        display a message informing the user that there are no messages
        {% endcomment %}
        {% ifnotequal max_page 1 %}
            <tr><td>
            {% comment %}
            If page 1 is displayed, there are no later posts, so hide the later/latest pagination links
            {% endcomment %}
            {% ifnotequal page_num 1 %}
                <div style="float: left;">
                    <a href="{% url "view_posts" page_num=1 %}">Latest</a>&#160;&#160;
                    <a href="{% url "view_posts" page_num=page_num|add:"-1" %}">Later</a>
                </div>
            {% endifnotequal %}
            {% comment %}
            If the current page is the maximum page, then there are no earlier post to display - hide these links
            {% endcomment %}
            {% ifnotequal page_num max_page %}
                <div style="float: right;">
                    <a href="{% url "view_posts" page_num=page_num|add:"1" %}">Earlier</a>&#160;&#160;
                    <a href="{% url "view_posts" page_num=max_page %}">Earliest</a>
                </div>
            {% endifnotequal %}
            </td></tr>
        {% endifnotequal %}
        </td></tr>
        </table>
    {% else %}
        <h2><i>There are no posts to display</i></h2>
    {% endif %}

{% endblock %}